### ISSUE TITLE
Make execute_git() public

### ISSUE THREAD

**Issue by danielhaap83** [keirlawson/rusty-git#9]
Hi,
I think it would be an good idea to make execute_git() public. In this way this library would provide some basic built-in commands plus the option to extend it with user defined commands.

Example:
I would need the command `git reset --hard`. This is not possible. I just have the options to:

- re-write the library my own -> bad
- take another library which will probably be based on libgit2 -> in my case bad as well

**Comment by danielhaap83** [comment]
See https://github.com/keirlawson/rusty-git/pull/10

**Comment by keirlawson** [comment]
The library just now certainly doesn't have comprehensive command coverage, but I think my preference is people PRing in the new commands that they need rather than going via a generic opt-out, that way the coverage slowly improves.  That said I appreciate the cycle of opening a PR, getting it approved, merged etc may be too slow in some cases so happy to add this on a pragmatic basis.

**Comment by keirlawson** [comment]
Closed by #10
